### PR TITLE
post (not host) about early history of MapSwipe

### PR DESCRIPTION
**Pull request by danbjoseph**
a blog post providing details about the early history of MapSwipe

### CODE REVIEW

**Review by jhenshall — APPROVED** [review]
I don't have the environment setup to check technically but it all looks good to me. Thanks for sorting this Dan!

**Comment by jhenshall** [comment]
Looks good! Going merge now. Thanks @danbjoseph!

**Comment by jhenshall** [comment]
Now on site but the image isn't loading for me. My internet is dodgy this morning though. @danbjoseph can you confirm before deleting the branch?

**Comment by danbjoseph** [comment]
minor mistake fixed with https://github.com/mapswipe/website/commit/a7f0261daad28aa15fbb797d1b954660d25ad3e6

**Pull request merged**
