### PR TITLE
Content review aug2023

### PR DESCRIPTION
**Pull request by Katbaloo**
- Addresses Copy edits to Home, Get Involved, and Data page
- Depends on nothing
## Changes

- Detailed list or prose of changes
image

- Breaking changes N/A
- Changes to configurations N/A

## This PR doesn't introduce any

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] codegen errors
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments
- [x] conflict markers

## This PR includes

- [ ] Translation

### CODE REVIEW

**Review by jhenshall — APPROVED** [review]
Looks good!

**Comment by danbjoseph** [comment]
@jhenshall did you run the `yarn generate:i18n` command? checking on transifex it looks like these changes are already reflected in the `en` source strings there. 

@kopitek8 @AdityaKhatri

**Comment by AdityaKhatri** [comment]
@danbjoseph ,  `yarn generate:i18n` is required if you modify/add/delete the key of the source string (English translation file). So, in this case, as the keys are not modified, the changes made will be reflected as soon as they are merged in the `main` branch.

**Comment by danbjoseph** [comment]
Thank you for explaining @AdityaKhatri. That makes sense.

**Pull request merged**
