### PR TITLE
update social to Mastodon

### PR DESCRIPTION
**Pull request by danbjoseph**
addresses #179

### CODE REVIEW

**Comment by danbjoseph** [comment]
@AdityaKhatri the `public/locales/hu/common.json` and `public/locales/ne/common.json`files both still have the `"twitter"` key/value pair. are those updated via the automated build process? is there a manual step to push the new `en` source strings to Transifex?

also, the build checks failed
```
Error: src/components/Footer/index.tsx(98,29): error TS2322: Type '{ children: Element; href: string; rel: string; variant: "icon"; target: string; title: DefaultTFuncReturn; }' is not assignable to type 'IntrinsicAttributes & Props'.
  Property 'rel' does not exist on type 'IntrinsicAttributes & Props'.
```
how do i add a `rel="me" ` attribute to the mastodon social link so that it will be marked as verified on our mastodon profile? i think there might be additional edit(s) needed on the `Link` template file?

**Comment by kopitek8** [comment]
@danbjoseph Please allow me to answer your Transifex query. 

To push new translations to Transifex, you would have to run `yarn generate:i18n`. Link to the read me file here: https://github.com/mapswipe/website#running. After that, the source strings will be edited and we will have to make changes via Transifex (for ne and hu). The updated translations will come after that.

**Comment by jhenshall** [comment]
Sorry, just getting to this but see review no longer needed. But also maybe relevant for a change we just tried but [build failed](https://github.com/mapswipe/website/actions/runs/5740768778).

So any changes made to the [content files](https://github.com/mapswipe/website/tree/main/public/locales/en) will not be reflected in Transifex without running the `yarn generate:i18n`?

**Comment by danbjoseph** [comment]
@jhenshall i took you off review for this because you posted in slack "I’m off for a few weeks now" 😄 
also, mostly needs technical review (you already voted yes in the governance team poll)

**Comment by AdityaKhatri** [comment]
@danbjoseph , looks like you've already fixed the issue with `rel`. 
The process that @kopitek8 mentioned should work. Let us know if you run into further issues.

**Comment by danbjoseph** [comment]
okay, i have run `yarn generate:i18n` and committed the results. @AdityaKhatri can you please review when you have a moment?

**Review by AdityaKhatri — APPROVED** [review]

**Comment by AdityaKhatri** [comment]
Looks good!

**Pull request merged**
